'use strict';

// The probability we submit to the Monash probabilistic competition.
//
// This is deliberately NOT the Elo model in model.js. Tested leave-one-season-out over 2022-2026,
// the best-scoring entry was a blend of the betting market and the Squiggle models that did best the
// previous season - and in every fold the blend gave the Elo ZERO weight: it adds nothing the market
// and those models do not already know. Scored against the real 2026 Monash field, game by game, the
// blend would have finished 2nd of 76 full-season tippers (0.2637 bits/game, 0.001 behind the
// winner) where the Elo finished 18th. So the site and /api/tips `hconfidence` stay pure Elo - that
// is what Cludestradamus is - and only the Monash entry uses this.
//
// Monash runs its own "BookieOdds" auto-tipper from normalised bookie odds and lists it among its
// "honest algorithms", so an odds-based entry is squarely within the comp's rules. Everything here
// is public information available before each game.
//
// Pure and dependency-free, shared by functions/api/tips.js and scripts/backtest-comp.mjs, so what
// is submitted and what was measured are the same code.

export const MARKET_SOURCE = 'Punters';   // Squiggle's name for the bookmakers' implied probability
export const MARKET_WEIGHT = 0.4;         // share of the blend on the market; the rest is the models
export const SHARPEN = 1.2;               // averaging pulls toward 0.5, so the blend is stretched back
export const EXCLUDE = ['Punters', 'Aggregate']; // never counted as "a model": market, and Squiggle's own average

// The Squiggle models to average, chosen as the 10 best by bits/game over the PREVIOUS season among
// those that tipped 90%+ of games. The optimum was flat from 8 to 15 models. Regenerate each February
// with `node scripts/backtest-comp.mjs --sources-for <year>` and add the new season here; a season
// with no entry falls back to the latest list, which still works, just slightly stale.
export const SOURCES_BY_SEASON = {
  // generated by `--sources-for 2027`: the 10 best of 2026
  2027: [
    "Don't Blame the Data", 's10', 'Matter of Stats', 'AFLalytics', 'The Wooden Finger',
    'Drop Kick Data', 'Wheelo Ratings', 'ZaphBot', 'The Cruncher', 'What Snoo Thinks',
  ],
};

export function sourcesFor(year) {
  if (SOURCES_BY_SEASON[year]) return { season: year, names: SOURCES_BY_SEASON[year] };
  const latest = Math.max(...Object.keys(SOURCES_BY_SEASON).map(Number).filter((y) => y <= year));
  return Number.isFinite(latest) ? { season: latest, names: SOURCES_BY_SEASON[latest] } : { season: null, names: [] };
}

const C = 0.01;
const clamp = (p) => Math.min(1 - C, Math.max(C, p));
const logit = (p) => Math.log(clamp(p) / (1 - clamp(p)));
const inv = (x) => 1 / (1 + Math.exp(-x));

/**
 * Blend one game. `market` is the market's home-win probability or null; `models` is a list of
 * model home-win probabilities (any that are missing are simply left out). Falls back to `fallback`
 * (the Elo) only when there is neither a market price nor a single model tip.
 */
export function blend(market, models, fallback) {
  const parts = [];
  if (market != null) parts.push([MARKET_WEIGHT, logit(market)]);
  if (models.length) parts.push([1 - MARKET_WEIGHT, models.reduce((s, p) => s + logit(p), 0) / models.length]);
  if (!parts.length) return { p: fallback, basis: 'elo' };
  const w = parts.reduce((s, [x]) => s + x, 0);
  const p = inv(SHARPEN * parts.reduce((s, [x, l]) => s + x * l, 0) / w);
  return { p, basis: market != null ? (models.length ? 'market+models' : 'market') : 'models' };
}
